[programs.devnet]
mymoneydapp = "BnpMpMkMx2NJ374B5BgApbM8bg825k3wV1GKoj4JpDQX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ectivi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
